INSERT INTO bosch.provincia (provincia_id, mercado_id, nombre)
VALUES (2, 1, 'Albacete'),
       (3, 1, 'Alicante/Alacant'),
       (4, 1, 'Almería'),
       (1, 1, 'Álava/Araba'),
       (33, 1, 'Asturias'),
       (5, 1, 'Ávila'),
       (6, 1, 'Badajoz'),
       (7, 1, 'Balears, Illes'),
       (8, 1, 'Barcelona'),
       (48, 1, 'Bizkaia'),
       (9, 1, 'Burgos'),
       (10, 1, 'Cáceres'),
       (11, 1, 'Cádiz'),
       (39, 1, 'Cantabria'),
       (12, 1, 'Castellón/Castelló'),
       (51, 1, 'Ceuta'),
       (13, 1, 'Ciudad Real'),
       (14, 1, 'Córdoba'),
       (15, 1, 'Coruña, A'),
       (16, 1, 'Cuenca'),
       (20, 1, 'Gipuzkoa'),
       (17, 1, 'Girona'),
       (18, 1, 'Granada'),
       (19, 1, 'Guadalajara'),
       (21, 1, 'Huelva'),
       (22, 1, 'Huesca'),
       (23, 1, 'Jaén'),
       (24, 1, 'León'),
       (27, 1, 'Lugo'),
       (25, 1, 'Lleida'),
       (28, 1, 'Madrid'),
       (29, 1, 'Málaga'),
       (52, 1, 'Melilla'),
       (30, 1, 'Murcia'),
       (31, 1, 'Navarra'),
       (32, 1, 'Ourense'),
       (34, 1, 'Palencia'),
       (35, 1, 'Palmas, Las'),
       (36, 1, 'Pontevedra'),
       (26, 1, 'Rioja, La'),
       (37, 1, 'Salamanca'),
       (38, 1, 'Santa Cruz de Tenerife'),
       (40, 1, 'Segovia'),
       (41, 1, 'Sevilla'),
       (42, 1, 'Soria'),
       (43, 1, 'Tarragona'),
       (44, 1, 'Teruel'),
       (45, 1, 'Toledo'),
       (46, 1, 'Valencia/València'),
       (47, 1, 'Valladolid'),
       (49, 1, 'Zamora'),
       (50, 1, 'Zaragoza');